.TH TTREE 1 TTREE\-2.3.2
.SH NAME
ttree \- a tree list of files and directories
.SH SYNOPSIS
.B ttree 
[
.B path
](optional) 
[
.BI args
] ...

.SH DESCRIPTION

.TP
.B -h, --help 
 Display help.

.TP
.B -v, --version
 Display version info.

.TP
.B -i \fI<number>\fB, --max-index=\fI<number>\fB
 Set max depth to which the tree should be displayed.

.TP
.B -f \fI<file/folder name>\fB, --find=\fI<file/folder name>\fB
 Search for specific file or folder name. Found file or folder will be highlighted.

.B CASE sensitive!

.TP
.B -s \fI<text>/<file_type>\fB, --search-in-file=\fI<text>/<file_type>\fB
 Search for text in files. File containing \fI<text>\fR will be highlighted.
\fI/\fR is required, use 
.B \fI<text>/\fB
for all file types

.B CASE sensitive!

.TP
.B -L, --leave-open
 Wait for user input to exit.

.TP
.B -a, --all
Display all files when using \fIsearch-in-file\fR or \fIfind\fR, including ones that do not fulfill the search criteria.

.B (ignored when not using search or find)

.TP
.B -o, --use-old-style
use old visual style without the pretty glyphs

.SH AUTHOR
Written by noTme.

.SH COPYRIGHT
MIT License

Copyright (c) 2022 Michal Bendik

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
